export const SET_OTODOMURL = "SET_OTODOMURL";

export const SET_LISTINGS = "SET_LISTINGS";

export const REQUEST_LISTINGS = "REQUEST_LISTINGS";
export const SUCCESS_LISTINGS = "SUCCESS_LISTINGS";
export const ERROR_LISTING = "ERROR_LISTING";
export const SET_DELETED = "SET_DELETED";
export const ADD_DELETED = "ADD_DELETED";
export const REMOVE_DELETED = "REMOVE_DELETED";

export const SET_SAVED = "SET_SAVED";
export const ADD_SAVED = "ADD_SAVED";
export const REMOVE_SAVED = "REMOVE_SAVED";
